name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - TBD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.0

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Log in to AWS ECR
        run: aws ecr get-login-password --region <cluster-region> | docker login --username AWS --password-stdin <ecr-url>

      - name: Build and push Docker image
        run: |
          docker build -t <ecr-url>/<docker-image-name>:latest .
          docker push <ecr-url>/<docker-image-name>:latest

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to AWS EC2 instance
        run: |
          ssh -i <ssh-private-key-file> -o StrictHostKeyChecking=no <ec2-user>@<ec2-instance-public-ip> "docker pull <ecr-url>/<docker-image-name>:latest && docker stop <container-name> && docker rm <container-name> || true && docker run -d --name <container-name> -p 80:80 <ecr-url>/<docker-image-name>:latest"
